### ISSUE TITLE
Bower 1.5.3 breaks my build.

### ISSUE THREAD

**Issue by rpiskule** [bower/bower.github.io#287]
I was using Bower 1.5.3, with Node v0.10. Everything was fine for a good amount of time.

2 days ago, our build broke. We were using a released version of Bower 1.5.3, and our build completely broke. I had to downgrade Bower to 1.5.2 to resolve this issue.

```
TypeError: Not an integer
at Object.fs.writeSync (fs.js:540:18)
at Function.writeFileSync [as sync] (/usr/lib/node_modules/bower/node_modules/write-file-atomic/index.js:114:10)
at Object.create.all.set (/usr/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:62:21)
at Object.Configstore (/usr/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:11)
at new Insight (/usr/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
at ensureInsight (/usr/lib/node_modules/bower/lib/util/analytics.js:25:19)
at Object.setup (/usr/lib/node_modules/bower/lib/util/analytics.js:41:9)
at Object. (/usr/lib/node_modules/bower/bin/bower:72:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
```

I reported this issue at the following site as well:
https://github.com/npm/write-file-atomic/issues/18

My overall concern here, is that the code was released. Bower was released. write-file-atomic was released.

I don't understand how released code could suddenly break. This is very concerning to me. There is a major security flaw with Bower if people on github can delete tags, change their code, and then re-release their code. Who's to stop people from changing their code to steal credit card numbers, db credentials, or other items?

**Comment by julmot** [comment]
Please ask this question in the [bower repository](https://github.com/bower/bower), as it's not related to the website.
